parameters:
    database_host: db
    database_port: 3306
    database_name: symfony
    database_user: symfony
    database_password: symfony
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: alexandre.corroy@gmail.com
    mailer_password: 123456789
    secret: ThisTokenIsNotSoSecretChangeIt
    mailer_encryption: ssl
    mailer_from: contact@todolist.com
    mailer_port: 465
    redis_host: redis://redis # or redis://127.0.0.1 for local redis
