# redis.yml
snc_redis:
  clients:
    default:
      type: predis
      alias: default
      dsn: "%redis_host%"
    doctrine:
      type: predis
      alias: doctrine
      dsn: "%redis_host%"
  doctrine:
    metadata_cache:
      client: doctrine
      entity_manager: default
      document_manager: default
    result_cache:
      client: doctrine
      entity_manager: default
    query_cache:
      client: doctrine
      entity_manager: default
