# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:

  _defaults:
    # automatically injects dependencies in your services
    autowire: true
    # automatically registers your services as commands, event subscribers, etc.
    autoconfigure: true
    # this means you cannot fetch services directly from the container via $container->get()
    # if you need to do this, you can override this setting on individual services
    public: false

  AppBundle\:
    resource: '../../src/AppBundle/*'
    exclude: '../../src/AppBundle/{Tests}'

  AppBundle\Controller\:
    resource: '../../src/AppBundle/Controller'
    public: true
    tags: ['controller.service_arguments']

  AppBundle\Service\Mailer:
    arguments:
      $mailerFrom: '%mailer_from%'

  AppBundle\DoctrineListener\TaskListener:
    arguments:
      - "@snc_redis.doctrine"
    tags:
      - { name: doctrine.event_listener, event: postFlush }

  AppBundle\DoctrineListener\UserListener:
    arguments:
      - "@snc_redis.doctrine"
    tags:
      - { name: doctrine.event_listener, event: postFlush }
