var classes = [
    {
        "name": "AppBundle\\AppBundle",
        "interface": false,
        "abstract": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Symfony\\Component\\HttpKernel\\Bundle\\Bundle"
        ],
        "parents": [
            "Symfony\\Component\\HttpKernel\\Bundle\\Bundle"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 4,
        "lloc": 4,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "AppBundle\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Controller\\DefaultController",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "indexAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\Routing\\Annotation\\Route"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller"
        ],
        "lcom": 1,
        "length": 3,
        "vocabulary": 3,
        "volume": 4.75,
        "difficulty": 0.5,
        "effort": 2.38,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 9.51,
        "number_operators": 1,
        "number_operands": 2,
        "number_operators_unique": 1,
        "number_operands_unique": 2,
        "cloc": 8,
        "loc": 16,
        "lloc": 8,
        "mi": 119.88,
        "mIwoC": 75.43,
        "commentWeight": 44.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "AppBundle\\Controller\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Controller\\SecurityController",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "loginAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "forgotPasswordAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "resetPasswordAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Request",
            "AppBundle\\Form\\Handler\\ForgotPasswordTypeHandler",
            "AppBundle\\Repository\\Interfaces\\UserRepositoryInterface",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Symfony\\Component\\HttpFoundation\\Response",
            "AppBundle\\Entity\\User",
            "Symfony\\Component\\HttpFoundation\\Request",
            "AppBundle\\Form\\Handler\\ResetPasswordTypeHandler",
            "Symfony\\Component\\Routing\\Annotation\\Route"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller"
        ],
        "lcom": 1,
        "length": 60,
        "vocabulary": 23,
        "volume": 271.41,
        "difficulty": 3.68,
        "effort": 997.45,
        "level": 0.27,
        "bugs": 0.09,
        "time": 55,
        "intelligentContent": 73.85,
        "number_operators": 11,
        "number_operands": 49,
        "number_operators_unique": 3,
        "number_operands_unique": 20,
        "cloc": 27,
        "loc": 55,
        "lloc": 28,
        "mi": 95.21,
        "mIwoC": 50.99,
        "commentWeight": 44.23,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 81,
        "relativeDataComplexity": 0.73,
        "relativeSystemComplexity": 81.73,
        "totalStructuralComplexity": 243,
        "totalDataComplexity": 2.2,
        "totalSystemComplexity": 245.2,
        "package": "AppBundle\\Controller\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 8,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Controller\\TaskController",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "listTaskNotDoneAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "listTaskDoneAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "editAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "toggleTaskAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "deleteTaskAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 8,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller",
            "Symfony\\Component\\HttpFoundation\\Response",
            "AppBundle\\Repository\\Interfaces\\TaskRepositoryInterface",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Symfony\\Component\\HttpFoundation\\Response",
            "AppBundle\\Repository\\Interfaces\\TaskRepositoryInterface",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Request",
            "AppBundle\\Form\\Handler\\TaskTypeHandler",
            "AppBundle\\Entity\\Task",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Symfony\\Component\\HttpFoundation\\Response",
            "AppBundle\\Entity\\Task",
            "Symfony\\Component\\HttpFoundation\\Request",
            "AppBundle\\Form\\Handler\\TaskTypeHandler",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Symfony\\Component\\HttpFoundation\\Response",
            "AppBundle\\Entity\\Task",
            "AppBundle\\Repository\\Interfaces\\TaskRepositoryInterface",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Symfony\\Component\\HttpFoundation\\Response",
            "AppBundle\\Entity\\Task",
            "AppBundle\\Repository\\Interfaces\\TaskRepositoryInterface",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\IsGranted"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller"
        ],
        "lcom": 1,
        "length": 75,
        "vocabulary": 21,
        "volume": 329.42,
        "difficulty": 5.33,
        "effort": 1756.93,
        "level": 0.19,
        "bugs": 0.11,
        "time": 98,
        "intelligentContent": 61.77,
        "number_operators": 11,
        "number_operands": 64,
        "number_operators_unique": 3,
        "number_operands_unique": 18,
        "cloc": 51,
        "loc": 93,
        "lloc": 42,
        "mi": 92.14,
        "mIwoC": 46.56,
        "commentWeight": 45.58,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 121,
        "relativeDataComplexity": 0.82,
        "relativeSystemComplexity": 121.82,
        "totalStructuralComplexity": 726,
        "totalDataComplexity": 4.92,
        "totalSystemComplexity": 730.92,
        "package": "AppBundle\\Controller\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 8,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Controller\\UserController",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "listAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "editAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller",
            "Symfony\\Component\\HttpFoundation\\Response",
            "AppBundle\\Repository\\Interfaces\\UserRepositoryInterface",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Request",
            "AppBundle\\Form\\Handler\\UserRegistrationTypeHandler",
            "AppBundle\\Entity\\User",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Symfony\\Component\\HttpFoundation\\Response",
            "AppBundle\\Entity\\User",
            "Symfony\\Component\\HttpFoundation\\Request",
            "AppBundle\\Form\\Handler\\UserUpdateTypeHandler",
            "Symfony\\Component\\Routing\\Annotation\\Route"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller"
        ],
        "lcom": 1,
        "length": 45,
        "vocabulary": 17,
        "volume": 183.94,
        "difficulty": 3.96,
        "effort": 729.17,
        "level": 0.25,
        "bugs": 0.06,
        "time": 41,
        "intelligentContent": 46.4,
        "number_operators": 8,
        "number_operands": 37,
        "number_operators_unique": 3,
        "number_operands_unique": 14,
        "cloc": 27,
        "loc": 52,
        "lloc": 25,
        "mi": 98.17,
        "mIwoC": 53.24,
        "commentWeight": 44.92,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 37,
        "totalStructuralComplexity": 108,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 111,
        "package": "AppBundle\\Controller\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 8,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\DataFixtures\\LoadUserData",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "load",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Doctrine\\Bundle\\FixturesBundle\\Fixture",
            "Symfony\\Component\\Security\\Core\\Encoder\\UserPasswordEncoderInterface",
            "Doctrine\\Common\\Persistence\\ObjectManager",
            "AppBundle\\Entity\\User",
            "AppBundle\\Entity\\User"
        ],
        "parents": [
            "Doctrine\\Bundle\\FixturesBundle\\Fixture"
        ],
        "lcom": 1,
        "length": 44,
        "vocabulary": 9,
        "volume": 139.48,
        "difficulty": 2.44,
        "effort": 339.97,
        "level": 0.41,
        "bugs": 0.05,
        "time": 19,
        "intelligentContent": 57.22,
        "number_operators": 5,
        "number_operands": 39,
        "number_operators_unique": 1,
        "number_operands_unique": 8,
        "cloc": 20,
        "loc": 51,
        "lloc": 31,
        "mi": 93.57,
        "mIwoC": 52.32,
        "commentWeight": 41.25,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0.11,
        "relativeSystemComplexity": 64.11,
        "totalStructuralComplexity": 128,
        "totalDataComplexity": 0.22,
        "totalSystemComplexity": 128.22,
        "package": "AppBundle\\DataFixtures\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\DataFixtures\\LoadUserTaskData",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "load",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Doctrine\\Bundle\\FixturesBundle\\Fixture",
            "Doctrine\\Common\\Persistence\\ObjectManager",
            "AppBundle\\Entity\\Task",
            "AppBundle\\Entity\\Task",
            "AppBundle\\Entity\\Task"
        ],
        "parents": [
            "Doctrine\\Bundle\\FixturesBundle\\Fixture"
        ],
        "lcom": 1,
        "length": 31,
        "vocabulary": 10,
        "volume": 102.98,
        "difficulty": 1.56,
        "effort": 160.19,
        "level": 0.64,
        "bugs": 0.03,
        "time": 9,
        "intelligentContent": 66.2,
        "number_operators": 3,
        "number_operands": 28,
        "number_operators_unique": 1,
        "number_operands_unique": 9,
        "cloc": 6,
        "loc": 29,
        "lloc": 23,
        "mi": 88.46,
        "mIwoC": 56.07,
        "commentWeight": 32.39,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.13,
        "relativeSystemComplexity": 49.13,
        "totalStructuralComplexity": 49,
        "totalDataComplexity": 0.13,
        "totalSystemComplexity": 49.13,
        "package": "AppBundle\\DataFixtures\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Entity\\Task",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setUser",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUser",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getId",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCreatedAt",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setCreatedAt",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getTitle",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setTitle",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getContent",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setContent",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isDone",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "toggle",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 12,
        "nbMethods": 8,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 8,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 3,
        "wmc": 12,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "AppBundle\\Entity\\Interfaces\\TaskInterface",
            "Datetime",
            "AppBundle\\Entity\\Interfaces\\UserInterface",
            "DateTime",
            "DateTime"
        ],
        "parents": [],
        "lcom": 1,
        "length": 36,
        "vocabulary": 8,
        "volume": 108,
        "difficulty": 3.83,
        "effort": 414,
        "level": 0.26,
        "bugs": 0.04,
        "time": 23,
        "intelligentContent": 28.17,
        "number_operators": 13,
        "number_operands": 23,
        "number_operators_unique": 2,
        "number_operands_unique": 6,
        "cloc": 63,
        "loc": 122,
        "lloc": 59,
        "mi": 91.86,
        "mIwoC": 47,
        "commentWeight": 44.86,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 6.42,
        "relativeSystemComplexity": 6.42,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 77,
        "totalSystemComplexity": 77,
        "package": "AppBundle\\Entity\\",
        "pageRank": 0.03,
        "afferentCoupling": 2,
        "efferentCoupling": 4,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "AppBundle\\Entity\\User",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getId",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUsername",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setUsername",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getSalt",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPassword",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setPassword",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getEmail",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setEmail",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getRoles",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "eraseCredentials",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getIsAdmin",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setIsAdmin",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setToken",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getToken",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 15,
        "nbMethods": 8,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 8,
        "nbMethodsGetter": 2,
        "nbMethodsSetters": 5,
        "wmc": 16,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "AppBundle\\Entity\\Interfaces\\UserInterface",
            "Doctrine\\Common\\Collections\\ArrayCollection"
        ],
        "parents": [],
        "lcom": 3,
        "length": 43,
        "vocabulary": 11,
        "volume": 148.76,
        "difficulty": 4.88,
        "effort": 725.18,
        "level": 0.21,
        "bugs": 0.05,
        "time": 40,
        "intelligentContent": 30.51,
        "number_operators": 17,
        "number_operands": 26,
        "number_operators_unique": 3,
        "number_operands_unique": 8,
        "cloc": 79,
        "loc": 153,
        "lloc": 74,
        "mi": 88.6,
        "mIwoC": 43.74,
        "commentWeight": 44.86,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 4.67,
        "relativeSystemComplexity": 5.67,
        "totalStructuralComplexity": 15,
        "totalDataComplexity": 70,
        "totalSystemComplexity": 85,
        "package": "AppBundle\\Entity\\",
        "pageRank": 0.03,
        "afferentCoupling": 3,
        "efferentCoupling": 2,
        "instability": 0.4,
        "violations": {}
    },
    {
        "name": "AppBundle\\Form\\ForgotPasswordType",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "buildForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Component\\Form\\AbstractType",
            "Symfony\\Component\\Form\\FormBuilderInterface"
        ],
        "parents": [
            "Symfony\\Component\\Form\\AbstractType"
        ],
        "lcom": 1,
        "length": 6,
        "vocabulary": 5,
        "volume": 13.93,
        "difficulty": 0,
        "effort": 0,
        "level": 1.67,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 23.22,
        "number_operators": 0,
        "number_operands": 6,
        "number_operators_unique": 0,
        "number_operands_unique": 5,
        "cloc": 7,
        "loc": 15,
        "lloc": 8,
        "mi": 115.73,
        "mIwoC": 72.16,
        "commentWeight": 43.58,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 2,
        "package": "AppBundle\\Form\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Form\\Handler\\ForgotPasswordTypeHandler",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "onSuccess",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "AppBundle\\Form\\Handler\\FormTypeHandler",
            "AppBundle\\Repository\\Interfaces\\UserRepositoryInterface",
            "Symfony\\Component\\Form\\FormFactoryInterface",
            "AppBundle\\Service\\Interfaces\\MailerInterface",
            "AppBundle\\Service\\Interfaces\\TokenGeneratorInterface",
            "Symfony\\Component\\Form\\FormInterface"
        ],
        "parents": [
            "AppBundle\\Form\\Handler\\FormTypeHandler"
        ],
        "lcom": 1,
        "length": 32,
        "vocabulary": 11,
        "volume": 110.7,
        "difficulty": 4.88,
        "effort": 539.67,
        "level": 0.21,
        "bugs": 0.04,
        "time": 30,
        "intelligentContent": 22.71,
        "number_operators": 6,
        "number_operands": 26,
        "number_operators_unique": 3,
        "number_operands_unique": 8,
        "cloc": 24,
        "loc": 51,
        "lloc": 27,
        "mi": 97.88,
        "mIwoC": 54.19,
        "commentWeight": 43.68,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 25.5,
        "totalStructuralComplexity": 75,
        "totalDataComplexity": 1.5,
        "totalSystemComplexity": 76.5,
        "package": "AppBundle\\Form\\Handler\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 6,
        "instability": 0.86,
        "violations": {}
    },
    {
        "name": "AppBundle\\Form\\Handler\\FormTypeHandler",
        "interface": false,
        "abstract": true,
        "methods": [
            {
                "name": "handle",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createView",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "returnForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "onSuccess",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "Symfony\\Component\\HttpFoundation\\Request",
            "this",
            "Symfony\\Component\\Form\\FormView",
            "Symfony\\Component\\Form\\FormInterface",
            "Symfony\\Component\\Form\\FormInterface"
        ],
        "parents": [],
        "lcom": 2,
        "length": 25,
        "vocabulary": 8,
        "volume": 75,
        "difficulty": 8.5,
        "effort": 637.5,
        "level": 0.12,
        "bugs": 0.03,
        "time": 35,
        "intelligentContent": 8.82,
        "number_operators": 8,
        "number_operands": 17,
        "number_operators_unique": 4,
        "number_operands_unique": 4,
        "cloc": 26,
        "loc": 52,
        "lloc": 26,
        "mi": 100.06,
        "mIwoC": 55.6,
        "commentWeight": 44.46,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.69,
        "relativeSystemComplexity": 36.69,
        "totalStructuralComplexity": 180,
        "totalDataComplexity": 3.43,
        "totalSystemComplexity": 183.43,
        "package": "AppBundle\\Form\\Handler\\",
        "pageRank": 0.04,
        "afferentCoupling": 5,
        "efferentCoupling": 4,
        "instability": 0.44,
        "violations": {}
    },
    {
        "name": "AppBundle\\Form\\Handler\\ResetPasswordTypeHandler",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "onSuccess",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "AppBundle\\Form\\Handler\\FormTypeHandler",
            "AppBundle\\Repository\\Interfaces\\UserRepositoryInterface",
            "Symfony\\Component\\Form\\FormFactoryInterface",
            "AppBundle\\Service\\Interfaces\\MailerInterface",
            "AppBundle\\Service\\Interfaces\\TokenGeneratorInterface",
            "Symfony\\Component\\Security\\Core\\Encoder\\EncoderFactoryInterface",
            "Symfony\\Component\\Form\\FormInterface"
        ],
        "parents": [
            "AppBundle\\Form\\Handler\\FormTypeHandler"
        ],
        "lcom": 1,
        "length": 43,
        "vocabulary": 13,
        "volume": 159.12,
        "difficulty": 5.25,
        "effort": 835.37,
        "level": 0.19,
        "bugs": 0.05,
        "time": 46,
        "intelligentContent": 30.31,
        "number_operators": 8,
        "number_operands": 35,
        "number_operators_unique": 3,
        "number_operands_unique": 10,
        "cloc": 27,
        "loc": 58,
        "lloc": 31,
        "mi": 95.33,
        "mIwoC": 51.78,
        "commentWeight": 43.54,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 81,
        "relativeDataComplexity": 0.33,
        "relativeSystemComplexity": 81.33,
        "totalStructuralComplexity": 243,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 244,
        "package": "AppBundle\\Form\\Handler\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 7,
        "instability": 0.88,
        "violations": {}
    },
    {
        "name": "AppBundle\\Form\\Handler\\TaskTypeHandler",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "onSuccess",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "AppBundle\\Form\\Handler\\FormTypeHandler",
            "AppBundle\\Repository\\Interfaces\\TaskRepositoryInterface",
            "Symfony\\Component\\Security\\Core\\Authentication\\Token\\Storage\\TokenStorageInterface",
            "Symfony\\Component\\Form\\FormFactoryInterface",
            "Symfony\\Component\\Form\\FormInterface"
        ],
        "parents": [
            "AppBundle\\Form\\Handler\\FormTypeHandler"
        ],
        "lcom": 1,
        "length": 24,
        "vocabulary": 8,
        "volume": 72,
        "difficulty": 5.7,
        "effort": 410.4,
        "level": 0.18,
        "bugs": 0.02,
        "time": 23,
        "intelligentContent": 12.63,
        "number_operators": 5,
        "number_operands": 19,
        "number_operators_unique": 3,
        "number_operands_unique": 5,
        "cloc": 21,
        "loc": 45,
        "lloc": 24,
        "mi": 100.19,
        "mIwoC": 56.62,
        "commentWeight": 43.58,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.38,
        "relativeSystemComplexity": 36.38,
        "totalStructuralComplexity": 108,
        "totalDataComplexity": 1.14,
        "totalSystemComplexity": 109.14,
        "package": "AppBundle\\Form\\Handler\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 5,
        "instability": 0.83,
        "violations": {}
    },
    {
        "name": "AppBundle\\Form\\Handler\\UserRegistrationTypeHandler",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "onSuccess",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "AppBundle\\Form\\Handler\\FormTypeHandler",
            "Symfony\\Component\\Security\\Core\\Encoder\\EncoderFactoryInterface",
            "AppBundle\\Repository\\Interfaces\\UserRepositoryInterface",
            "AppBundle\\Service\\Interfaces\\PasswordGeneratorInterface",
            "AppBundle\\Service\\Interfaces\\MailerInterface",
            "Symfony\\Component\\Form\\FormFactoryInterface",
            "Symfony\\Component\\Form\\FormInterface"
        ],
        "parents": [
            "AppBundle\\Form\\Handler\\FormTypeHandler"
        ],
        "lcom": 1,
        "length": 42,
        "vocabulary": 12,
        "volume": 150.57,
        "difficulty": 3.4,
        "effort": 511.93,
        "level": 0.29,
        "bugs": 0.05,
        "time": 28,
        "intelligentContent": 44.28,
        "number_operators": 8,
        "number_operands": 34,
        "number_operators_unique": 2,
        "number_operands_unique": 10,
        "cloc": 27,
        "loc": 57,
        "lloc": 30,
        "mi": 96.16,
        "mIwoC": 52.4,
        "commentWeight": 43.77,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0.37,
        "relativeSystemComplexity": 64.37,
        "totalStructuralComplexity": 192,
        "totalDataComplexity": 1.11,
        "totalSystemComplexity": 193.11,
        "package": "AppBundle\\Form\\Handler\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 7,
        "instability": 0.88,
        "violations": {}
    },
    {
        "name": "AppBundle\\Form\\Handler\\UserUpdateTypeHandler",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "onSuccess",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "AppBundle\\Form\\Handler\\FormTypeHandler",
            "AppBundle\\Repository\\Interfaces\\UserRepositoryInterface",
            "AppBundle\\Service\\Interfaces\\MailerInterface",
            "Symfony\\Component\\Form\\FormFactoryInterface",
            "Symfony\\Component\\Form\\FormInterface"
        ],
        "parents": [
            "AppBundle\\Form\\Handler\\FormTypeHandler"
        ],
        "lcom": 1,
        "length": 23,
        "vocabulary": 9,
        "volume": 72.91,
        "difficulty": 2.71,
        "effort": 197.89,
        "level": 0.37,
        "bugs": 0.02,
        "time": 11,
        "intelligentContent": 26.86,
        "number_operators": 4,
        "number_operands": 19,
        "number_operators_unique": 2,
        "number_operands_unique": 7,
        "cloc": 21,
        "loc": 43,
        "lloc": 22,
        "mi": 101.7,
        "mIwoC": 57.54,
        "commentWeight": 44.16,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.67,
        "relativeSystemComplexity": 9.67,
        "totalStructuralComplexity": 27,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 29,
        "package": "AppBundle\\Form\\Handler\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 5,
        "instability": 0.83,
        "violations": {}
    },
    {
        "name": "AppBundle\\Form\\ResetPasswordType",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "buildForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Component\\Form\\AbstractType",
            "Symfony\\Component\\Form\\FormBuilderInterface"
        ],
        "parents": [
            "Symfony\\Component\\Form\\AbstractType"
        ],
        "lcom": 1,
        "length": 16,
        "vocabulary": 13,
        "volume": 59.21,
        "difficulty": 0,
        "effort": 0,
        "level": 1.63,
        "bugs": 0.02,
        "time": 0,
        "intelligentContent": 96.21,
        "number_operators": 0,
        "number_operands": 16,
        "number_operators_unique": 0,
        "number_operands_unique": 13,
        "cloc": 7,
        "loc": 15,
        "lloc": 8,
        "mi": 111.33,
        "mIwoC": 67.76,
        "commentWeight": 43.58,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 2,
        "package": "AppBundle\\Form\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Form\\TaskAddType",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "buildForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Component\\Form\\AbstractType",
            "Symfony\\Component\\Form\\FormBuilderInterface"
        ],
        "parents": [
            "Symfony\\Component\\Form\\AbstractType"
        ],
        "lcom": 1,
        "length": 5,
        "vocabulary": 4,
        "volume": 10,
        "difficulty": 0,
        "effort": 0,
        "level": 1.6,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 16,
        "number_operators": 0,
        "number_operands": 5,
        "number_operators_unique": 0,
        "number_operands_unique": 4,
        "cloc": 7,
        "loc": 15,
        "lloc": 8,
        "mi": 116.74,
        "mIwoC": 73.16,
        "commentWeight": 43.58,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 2,
        "package": "AppBundle\\Form\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Form\\UserRegistrationType",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "buildForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Component\\Form\\AbstractType",
            "Symfony\\Component\\Form\\FormBuilderInterface"
        ],
        "parents": [
            "Symfony\\Component\\Form\\AbstractType"
        ],
        "lcom": 1,
        "length": 13,
        "vocabulary": 10,
        "volume": 43.19,
        "difficulty": 0,
        "effort": 0,
        "level": 1.54,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 66.44,
        "number_operators": 0,
        "number_operands": 13,
        "number_operators_unique": 0,
        "number_operands_unique": 10,
        "cloc": 7,
        "loc": 15,
        "lloc": 8,
        "mi": 112.29,
        "mIwoC": 68.71,
        "commentWeight": 43.58,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 2,
        "package": "AppBundle\\Form\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Repository\\TaskRepository",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isNewEntity",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "save",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "flush",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "delete",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "findAllTask",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepository",
            "AppBundle\\Repository\\Interfaces\\TaskRepositoryInterface",
            "Symfony\\Bridge\\Doctrine\\RegistryInterface",
            "parent",
            "AppBundle\\Entity\\Interfaces\\TaskInterface",
            "AppBundle\\Entity\\Interfaces\\TaskInterface",
            "this",
            "this",
            "AppBundle\\Entity\\Interfaces\\TaskInterface",
            "this"
        ],
        "parents": [
            "Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepository"
        ],
        "lcom": 3,
        "length": 29,
        "vocabulary": 11,
        "volume": 100.32,
        "difficulty": 6.86,
        "effort": 687.93,
        "level": 0.15,
        "bugs": 0.03,
        "time": 38,
        "intelligentContent": 14.63,
        "number_operators": 5,
        "number_operands": 24,
        "number_operators_unique": 4,
        "number_operands_unique": 7,
        "cloc": 23,
        "loc": 56,
        "lloc": 33,
        "mi": 94.47,
        "mIwoC": 52.59,
        "commentWeight": 41.88,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 144,
        "relativeDataComplexity": 0.22,
        "relativeSystemComplexity": 144.22,
        "totalStructuralComplexity": 864,
        "totalDataComplexity": 1.31,
        "totalSystemComplexity": 865.31,
        "package": "AppBundle\\Repository\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Repository\\UserRepository",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "save",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUserByEmail",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUserByToken",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "listUsers",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepository",
            "AppBundle\\Repository\\Interfaces\\UserRepositoryInterface",
            "Symfony\\Bridge\\Doctrine\\RegistryInterface",
            "parent",
            "AppBundle\\Entity\\Interfaces\\UserInterface"
        ],
        "parents": [
            "Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepository"
        ],
        "lcom": 3,
        "length": 36,
        "vocabulary": 13,
        "volume": 133.22,
        "difficulty": 6.22,
        "effort": 828.9,
        "level": 0.16,
        "bugs": 0.04,
        "time": 46,
        "intelligentContent": 21.41,
        "number_operators": 8,
        "number_operands": 28,
        "number_operators_unique": 4,
        "number_operands_unique": 9,
        "cloc": 18,
        "loc": 48,
        "lloc": 30,
        "mi": 93.27,
        "mIwoC": 52.63,
        "commentWeight": 40.63,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 121,
        "relativeDataComplexity": 0.32,
        "relativeSystemComplexity": 121.32,
        "totalStructuralComplexity": 605,
        "totalDataComplexity": 1.58,
        "totalSystemComplexity": 606.58,
        "package": "AppBundle\\Repository\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Security\\TaskVoter",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "supports",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "voteOnAttribute",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "canDelete",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 3,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 10,
        "ccn": 8,
        "ccnMethodMax": 4,
        "externals": [
            "Symfony\\Component\\Security\\Core\\Authorization\\Voter\\Voter",
            "Symfony\\Component\\Security\\Core\\Authentication\\Token\\TokenInterface",
            "LogicException",
            "AppBundle\\Entity\\Interfaces\\TaskInterface",
            "AppBundle\\Entity\\Interfaces\\UserInterface"
        ],
        "parents": [
            "Symfony\\Component\\Security\\Core\\Authorization\\Voter\\Voter"
        ],
        "lcom": 2,
        "length": 42,
        "vocabulary": 16,
        "volume": 168,
        "difficulty": 9.72,
        "effort": 1633.33,
        "level": 0.1,
        "bugs": 0.06,
        "time": 91,
        "intelligentContent": 17.28,
        "number_operators": 17,
        "number_operands": 25,
        "number_operators_unique": 7,
        "number_operands_unique": 9,
        "cloc": 26,
        "loc": 61,
        "lloc": 35,
        "mi": 92.04,
        "mIwoC": 49.66,
        "commentWeight": 42.38,
        "kanDefect": 0.65,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 2.33,
        "relativeSystemComplexity": 11.33,
        "totalStructuralComplexity": 27,
        "totalDataComplexity": 7,
        "totalSystemComplexity": 34,
        "package": "AppBundle\\Security\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Service\\Mailer",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "sendMail",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getMailerFrom",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "AppBundle\\Service\\Interfaces\\MailerInterface",
            "Twig_Environment",
            "Swift_Mailer",
            "AppBundle\\Entity\\Interfaces\\UserInterface",
            "Swift_Message"
        ],
        "parents": [],
        "lcom": 1,
        "length": 33,
        "vocabulary": 14,
        "volume": 125.64,
        "difficulty": 3.55,
        "effort": 445.46,
        "level": 0.28,
        "bugs": 0.04,
        "time": 25,
        "intelligentContent": 35.44,
        "number_operators": 7,
        "number_operands": 26,
        "number_operators_unique": 3,
        "number_operands_unique": 11,
        "cloc": 21,
        "loc": 43,
        "lloc": 22,
        "mi": 100.04,
        "mIwoC": 55.88,
        "commentWeight": 44.16,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 81,
        "relativeDataComplexity": 0.3,
        "relativeSystemComplexity": 81.3,
        "totalStructuralComplexity": 243,
        "totalDataComplexity": 0.9,
        "totalSystemComplexity": 243.9,
        "package": "AppBundle\\Service\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Service\\PasswordGenerator",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "generate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "AppBundle\\Service\\Interfaces\\PasswordGeneratorInterface"
        ],
        "parents": [],
        "lcom": 1,
        "length": 8,
        "vocabulary": 7,
        "volume": 22.46,
        "difficulty": 1.2,
        "effort": 26.95,
        "level": 0.83,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 18.72,
        "number_operators": 2,
        "number_operands": 6,
        "number_operators_unique": 2,
        "number_operands_unique": 5,
        "cloc": 9,
        "loc": 19,
        "lloc": 10,
        "mi": 112.36,
        "mIwoC": 68.59,
        "commentWeight": 43.77,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "AppBundle\\Service\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Service\\TokenGenerator",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "generateToken",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "AppBundle\\Service\\Interfaces\\TokenGeneratorInterface",
            "AppBundle\\Entity\\Interfaces\\UserInterface"
        ],
        "parents": [],
        "lcom": 1,
        "length": 9,
        "vocabulary": 6,
        "volume": 23.26,
        "difficulty": 2.5,
        "effort": 58.16,
        "level": 0.4,
        "bugs": 0.01,
        "time": 3,
        "intelligentContent": 9.31,
        "number_operators": 4,
        "number_operands": 5,
        "number_operators_unique": 3,
        "number_operands_unique": 3,
        "cloc": 6,
        "loc": 15,
        "lloc": 9,
        "mi": 111,
        "mIwoC": 69.48,
        "commentWeight": 41.52,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 2,
        "package": "AppBundle\\Service\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    }
]