var classes = [
    {
        "name": "AppBundle\\AppBundle",
        "interface": false,
        "abstract": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Symfony\\Component\\HttpKernel\\Bundle\\Bundle"
        ],
        "parents": [
            "Symfony\\Component\\HttpKernel\\Bundle\\Bundle"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 4,
        "lloc": 4,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "AppBundle\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Controller\\DefaultController",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "indexAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\Routing\\Annotation\\Route"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller"
        ],
        "lcom": 1,
        "length": 7,
        "vocabulary": 6,
        "volume": 18.09,
        "difficulty": 1.25,
        "effort": 22.62,
        "level": 0.8,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 14.48,
        "number_operators": 2,
        "number_operands": 5,
        "number_operators_unique": 2,
        "number_operands_unique": 4,
        "cloc": 8,
        "loc": 17,
        "lloc": 9,
        "mi": 113.93,
        "mIwoC": 70.25,
        "commentWeight": 43.68,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.33,
        "relativeSystemComplexity": 4.33,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 0.33,
        "totalSystemComplexity": 4.33,
        "package": "AppBundle\\Controller\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Controller\\SecurityController",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "loginAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "forgotPasswordAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "resetPasswordAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Request",
            "AppBundle\\Form\\Handler\\ForgotPasswordTypeHandler",
            "AppBundle\\Repository\\Interfaces\\UserRepositoryInterface",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Symfony\\Component\\HttpFoundation\\Response",
            "AppBundle\\Entity\\User",
            "Symfony\\Component\\HttpFoundation\\Request",
            "AppBundle\\Form\\Handler\\ResetPasswordTypeHandler",
            "Symfony\\Component\\Routing\\Annotation\\Route"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller"
        ],
        "lcom": 1,
        "length": 57,
        "vocabulary": 23,
        "volume": 257.84,
        "difficulty": 3.53,
        "effort": 908.9,
        "level": 0.28,
        "bugs": 0.09,
        "time": 50,
        "intelligentContent": 73.15,
        "number_operators": 10,
        "number_operands": 47,
        "number_operators_unique": 3,
        "number_operands_unique": 20,
        "cloc": 27,
        "loc": 54,
        "lloc": 27,
        "mi": 95.95,
        "mIwoC": 51.49,
        "commentWeight": 44.46,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 81,
        "relativeDataComplexity": 0.73,
        "relativeSystemComplexity": 81.73,
        "totalStructuralComplexity": 243,
        "totalDataComplexity": 2.2,
        "totalSystemComplexity": 245.2,
        "package": "AppBundle\\Controller\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 8,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Controller\\TaskController",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "listTaskNotDoneAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "listTaskDoneAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "editAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "toggleTaskAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "deleteTaskAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 8,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller",
            "Symfony\\Component\\HttpFoundation\\Response",
            "AppBundle\\Repository\\Interfaces\\TaskRepositoryInterface",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Symfony\\Component\\HttpFoundation\\Response",
            "AppBundle\\Repository\\Interfaces\\TaskRepositoryInterface",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Request",
            "AppBundle\\Form\\Handler\\TaskTypeHandler",
            "AppBundle\\Entity\\Task",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Symfony\\Component\\HttpFoundation\\Response",
            "AppBundle\\Entity\\Task",
            "Symfony\\Component\\HttpFoundation\\Request",
            "AppBundle\\Form\\Handler\\TaskTypeHandler",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Symfony\\Component\\HttpFoundation\\Response",
            "AppBundle\\Entity\\Task",
            "AppBundle\\Repository\\Interfaces\\TaskRepositoryInterface",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Symfony\\Component\\HttpFoundation\\Response",
            "AppBundle\\Entity\\Task",
            "AppBundle\\Repository\\Interfaces\\TaskRepositoryInterface",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\IsGranted"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller"
        ],
        "lcom": 1,
        "length": 80,
        "vocabulary": 22,
        "volume": 356.75,
        "difficulty": 5.37,
        "effort": 1915.21,
        "level": 0.19,
        "bugs": 0.12,
        "time": 106,
        "intelligentContent": 66.45,
        "number_operators": 12,
        "number_operands": 68,
        "number_operators_unique": 3,
        "number_operands_unique": 19,
        "cloc": 51,
        "loc": 94,
        "lloc": 43,
        "mi": 91.55,
        "mIwoC": 46.09,
        "commentWeight": 45.45,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 144,
        "relativeDataComplexity": 0.76,
        "relativeSystemComplexity": 144.76,
        "totalStructuralComplexity": 864,
        "totalDataComplexity": 4.54,
        "totalSystemComplexity": 868.54,
        "package": "AppBundle\\Controller\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 8,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Controller\\UserController",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "listAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "editAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller",
            "Symfony\\Component\\HttpFoundation\\Response",
            "AppBundle\\Repository\\Interfaces\\UserRepositoryInterface",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Request",
            "AppBundle\\Form\\Handler\\UserRegistrationTypeHandler",
            "AppBundle\\Entity\\User",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Symfony\\Component\\HttpFoundation\\Response",
            "AppBundle\\Entity\\User",
            "Symfony\\Component\\HttpFoundation\\Request",
            "AppBundle\\Form\\Handler\\UserUpdateTypeHandler",
            "Symfony\\Component\\Routing\\Annotation\\Route"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller"
        ],
        "lcom": 1,
        "length": 46,
        "vocabulary": 18,
        "volume": 191.82,
        "difficulty": 3.8,
        "effort": 728.9,
        "level": 0.26,
        "bugs": 0.06,
        "time": 40,
        "intelligentContent": 50.48,
        "number_operators": 8,
        "number_operands": 38,
        "number_operators_unique": 3,
        "number_operands_unique": 15,
        "cloc": 27,
        "loc": 52,
        "lloc": 25,
        "mi": 98.04,
        "mIwoC": 53.12,
        "commentWeight": 44.92,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.88,
        "relativeSystemComplexity": 49.88,
        "totalStructuralComplexity": 147,
        "totalDataComplexity": 2.63,
        "totalSystemComplexity": 149.63,
        "package": "AppBundle\\Controller\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 8,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\DataFixtures\\LoadUserData",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "load",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Doctrine\\Bundle\\FixturesBundle\\Fixture",
            "Symfony\\Component\\Security\\Core\\Encoder\\UserPasswordEncoderInterface",
            "Doctrine\\Common\\Persistence\\ObjectManager",
            "AppBundle\\Entity\\User",
            "AppBundle\\Entity\\User"
        ],
        "parents": [
            "Doctrine\\Bundle\\FixturesBundle\\Fixture"
        ],
        "lcom": 1,
        "length": 44,
        "vocabulary": 9,
        "volume": 139.48,
        "difficulty": 2.44,
        "effort": 339.97,
        "level": 0.41,
        "bugs": 0.05,
        "time": 19,
        "intelligentContent": 57.22,
        "number_operators": 5,
        "number_operands": 39,
        "number_operators_unique": 1,
        "number_operands_unique": 8,
        "cloc": 20,
        "loc": 51,
        "lloc": 31,
        "mi": 93.57,
        "mIwoC": 52.32,
        "commentWeight": 41.25,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0.11,
        "relativeSystemComplexity": 64.11,
        "totalStructuralComplexity": 128,
        "totalDataComplexity": 0.22,
        "totalSystemComplexity": 128.22,
        "package": "AppBundle\\DataFixtures\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\DataFixtures\\LoadUserTaskData",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "load",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Doctrine\\Bundle\\FixturesBundle\\Fixture",
            "Doctrine\\Common\\Persistence\\ObjectManager",
            "AppBundle\\Entity\\Task",
            "AppBundle\\Entity\\Task",
            "AppBundle\\Entity\\Task"
        ],
        "parents": [
            "Doctrine\\Bundle\\FixturesBundle\\Fixture"
        ],
        "lcom": 1,
        "length": 31,
        "vocabulary": 10,
        "volume": 102.98,
        "difficulty": 1.56,
        "effort": 160.19,
        "level": 0.64,
        "bugs": 0.03,
        "time": 9,
        "intelligentContent": 66.2,
        "number_operators": 3,
        "number_operands": 28,
        "number_operators_unique": 1,
        "number_operands_unique": 9,
        "cloc": 6,
        "loc": 29,
        "lloc": 23,
        "mi": 88.46,
        "mIwoC": 56.07,
        "commentWeight": 32.39,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.13,
        "relativeSystemComplexity": 49.13,
        "totalStructuralComplexity": 49,
        "totalDataComplexity": 0.13,
        "totalSystemComplexity": 49.13,
        "package": "AppBundle\\DataFixtures\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\DoctrineListener\\TaskListener",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "postFlush",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 10,
        "vocabulary": 6,
        "volume": 25.85,
        "difficulty": 0.9,
        "effort": 23.26,
        "level": 1.11,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 28.72,
        "number_operators": 1,
        "number_operands": 9,
        "number_operators_unique": 1,
        "number_operands_unique": 5,
        "cloc": 14,
        "loc": 28,
        "lloc": 14,
        "mi": 109.43,
        "mIwoC": 64.97,
        "commentWeight": 44.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.25,
        "relativeSystemComplexity": 1.25,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 2.5,
        "package": "AppBundle\\DoctrineListener\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "AppBundle\\DoctrineListener\\UserListener",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "postFlush",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 7,
        "vocabulary": 5,
        "volume": 16.25,
        "difficulty": 0.75,
        "effort": 12.19,
        "level": 1.33,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 21.67,
        "number_operators": 1,
        "number_operands": 6,
        "number_operators_unique": 1,
        "number_operands_unique": 4,
        "cloc": 14,
        "loc": 27,
        "lloc": 13,
        "mi": 112,
        "mIwoC": 67.09,
        "commentWeight": 44.91,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.25,
        "relativeSystemComplexity": 1.25,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 2.5,
        "package": "AppBundle\\DoctrineListener\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "AppBundle\\Entity\\Task",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setUser",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUser",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getId",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCreatedAt",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setCreatedAt",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getTitle",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setTitle",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getContent",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setContent",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isDone",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "toggle",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 12,
        "nbMethods": 8,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 8,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 3,
        "wmc": 12,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "AppBundle\\Entity\\Interfaces\\TaskInterface",
            "Datetime",
            "AppBundle\\Entity\\Interfaces\\UserInterface",
            "DateTime",
            "DateTime"
        ],
        "parents": [],
        "lcom": 1,
        "length": 36,
        "vocabulary": 8,
        "volume": 108,
        "difficulty": 3.83,
        "effort": 414,
        "level": 0.26,
        "bugs": 0.04,
        "time": 23,
        "intelligentContent": 28.17,
        "number_operators": 13,
        "number_operands": 23,
        "number_operators_unique": 2,
        "number_operands_unique": 6,
        "cloc": 63,
        "loc": 122,
        "lloc": 59,
        "mi": 91.86,
        "mIwoC": 47,
        "commentWeight": 44.86,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 6.42,
        "relativeSystemComplexity": 6.42,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 77,
        "totalSystemComplexity": 77,
        "package": "AppBundle\\Entity\\",
        "pageRank": 0.03,
        "afferentCoupling": 2,
        "efferentCoupling": 4,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "AppBundle\\Entity\\User",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getId",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUsername",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setUsername",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getSalt",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPassword",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setPassword",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getEmail",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setEmail",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getRoles",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "eraseCredentials",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getIsAdmin",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setIsAdmin",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setToken",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getToken",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 15,
        "nbMethods": 8,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 8,
        "nbMethodsGetter": 2,
        "nbMethodsSetters": 5,
        "wmc": 16,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "AppBundle\\Entity\\Interfaces\\UserInterface",
            "Doctrine\\Common\\Collections\\ArrayCollection"
        ],
        "parents": [],
        "lcom": 3,
        "length": 43,
        "vocabulary": 11,
        "volume": 148.76,
        "difficulty": 4.88,
        "effort": 725.18,
        "level": 0.21,
        "bugs": 0.05,
        "time": 40,
        "intelligentContent": 30.51,
        "number_operators": 17,
        "number_operands": 26,
        "number_operators_unique": 3,
        "number_operands_unique": 8,
        "cloc": 79,
        "loc": 153,
        "lloc": 74,
        "mi": 88.6,
        "mIwoC": 43.74,
        "commentWeight": 44.86,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 4.67,
        "relativeSystemComplexity": 5.67,
        "totalStructuralComplexity": 15,
        "totalDataComplexity": 70,
        "totalSystemComplexity": 85,
        "package": "AppBundle\\Entity\\",
        "pageRank": 0.03,
        "afferentCoupling": 3,
        "efferentCoupling": 2,
        "instability": 0.4,
        "violations": {}
    },
    {
        "name": "AppBundle\\Form\\ForgotPasswordType",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "buildForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Component\\Form\\AbstractType",
            "Symfony\\Component\\Form\\FormBuilderInterface"
        ],
        "parents": [
            "Symfony\\Component\\Form\\AbstractType"
        ],
        "lcom": 1,
        "length": 6,
        "vocabulary": 5,
        "volume": 13.93,
        "difficulty": 0,
        "effort": 0,
        "level": 1.67,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 23.22,
        "number_operators": 0,
        "number_operands": 6,
        "number_operators_unique": 0,
        "number_operands_unique": 5,
        "cloc": 7,
        "loc": 15,
        "lloc": 8,
        "mi": 115.73,
        "mIwoC": 72.16,
        "commentWeight": 43.58,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 2,
        "package": "AppBundle\\Form\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Form\\Handler\\ForgotPasswordTypeHandler",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "onSuccess",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getFormType",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "AppBundle\\Form\\Handler\\FormTypeHandler",
            "AppBundle\\Repository\\Interfaces\\UserRepositoryInterface",
            "Symfony\\Component\\Form\\FormFactoryInterface",
            "AppBundle\\Service\\Interfaces\\MailerInterface",
            "AppBundle\\Service\\Interfaces\\TokenGeneratorInterface"
        ],
        "parents": [
            "AppBundle\\Form\\Handler\\FormTypeHandler"
        ],
        "lcom": 2,
        "length": 26,
        "vocabulary": 11,
        "volume": 89.95,
        "difficulty": 3.94,
        "effort": 354.16,
        "level": 0.25,
        "bugs": 0.03,
        "time": 20,
        "intelligentContent": 22.84,
        "number_operators": 5,
        "number_operands": 21,
        "number_operators_unique": 3,
        "number_operands_unique": 8,
        "cloc": 21,
        "loc": 46,
        "lloc": 25,
        "mi": 98.84,
        "mIwoC": 55.55,
        "commentWeight": 43.29,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.53,
        "relativeSystemComplexity": 16.53,
        "totalStructuralComplexity": 48,
        "totalDataComplexity": 1.6,
        "totalSystemComplexity": 49.6,
        "package": "AppBundle\\Form\\Handler\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 5,
        "instability": 0.83,
        "violations": {}
    },
    {
        "name": "AppBundle\\Form\\Handler\\FormTypeHandler",
        "interface": false,
        "abstract": true,
        "methods": [
            {
                "name": "handle",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createView",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getFormFactory",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "onSuccess",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getFormType",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "Symfony\\Component\\HttpFoundation\\Request",
            "Symfony\\Component\\Form\\FormView",
            "Symfony\\Component\\Form\\FormFactoryInterface",
            "Doctrine\\Common\\Annotations\\Annotation\\Required"
        ],
        "parents": [],
        "lcom": 1,
        "length": 24,
        "vocabulary": 8,
        "volume": 72,
        "difficulty": 8.5,
        "effort": 612,
        "level": 0.12,
        "bugs": 0.02,
        "time": 34,
        "intelligentContent": 8.47,
        "number_operators": 7,
        "number_operands": 17,
        "number_operators_unique": 4,
        "number_operands_unique": 4,
        "cloc": 28,
        "loc": 54,
        "lloc": 26,
        "mi": 100.63,
        "mIwoC": 55.73,
        "commentWeight": 44.91,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.48,
        "relativeSystemComplexity": 49.48,
        "totalStructuralComplexity": 245,
        "totalDataComplexity": 2.38,
        "totalSystemComplexity": 247.38,
        "package": "AppBundle\\Form\\Handler\\",
        "pageRank": 0.05,
        "afferentCoupling": 5,
        "efferentCoupling": 4,
        "instability": 0.44,
        "violations": {}
    },
    {
        "name": "AppBundle\\Form\\Handler\\ResetPasswordTypeHandler",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "onSuccess",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getFormType",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "AppBundle\\Form\\Handler\\FormTypeHandler",
            "AppBundle\\Repository\\Interfaces\\UserRepositoryInterface",
            "AppBundle\\Service\\Interfaces\\MailerInterface",
            "AppBundle\\Service\\Interfaces\\TokenGeneratorInterface",
            "Symfony\\Component\\Security\\Core\\Encoder\\EncoderFactoryInterface"
        ],
        "parents": [
            "AppBundle\\Form\\Handler\\FormTypeHandler"
        ],
        "lcom": 2,
        "length": 36,
        "vocabulary": 12,
        "volume": 129.06,
        "difficulty": 4.83,
        "effort": 623.78,
        "level": 0.21,
        "bugs": 0.04,
        "time": 35,
        "intelligentContent": 26.7,
        "number_operators": 7,
        "number_operands": 29,
        "number_operators_unique": 3,
        "number_operands_unique": 9,
        "cloc": 24,
        "loc": 53,
        "lloc": 29,
        "mi": 96.23,
        "mIwoC": 53.05,
        "commentWeight": 43.18,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0.3,
        "relativeSystemComplexity": 64.3,
        "totalStructuralComplexity": 192,
        "totalDataComplexity": 0.89,
        "totalSystemComplexity": 192.89,
        "package": "AppBundle\\Form\\Handler\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 5,
        "instability": 0.83,
        "violations": {}
    },
    {
        "name": "AppBundle\\Form\\Handler\\TaskTypeHandler",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "onSuccess",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getFormType",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "AppBundle\\Form\\Handler\\FormTypeHandler",
            "AppBundle\\Repository\\Interfaces\\TaskRepositoryInterface",
            "Symfony\\Component\\Security\\Core\\Authentication\\Token\\Storage\\TokenStorageInterface"
        ],
        "parents": [
            "AppBundle\\Form\\Handler\\FormTypeHandler"
        ],
        "lcom": 2,
        "length": 17,
        "vocabulary": 7,
        "volume": 47.73,
        "difficulty": 4.88,
        "effort": 232.66,
        "level": 0.21,
        "bugs": 0.02,
        "time": 13,
        "intelligentContent": 9.79,
        "number_operators": 4,
        "number_operands": 13,
        "number_operators_unique": 3,
        "number_operands_unique": 4,
        "cloc": 18,
        "loc": 40,
        "lloc": 22,
        "mi": 101.79,
        "mIwoC": 58.69,
        "commentWeight": 43.1,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.33,
        "relativeSystemComplexity": 25.33,
        "totalStructuralComplexity": 75,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 76,
        "package": "AppBundle\\Form\\Handler\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "AppBundle\\Form\\Handler\\UserRegistrationTypeHandler",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "onSuccess",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getFormType",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "AppBundle\\Form\\Handler\\FormTypeHandler",
            "Symfony\\Component\\Security\\Core\\Encoder\\EncoderFactoryInterface",
            "AppBundle\\Repository\\Interfaces\\UserRepositoryInterface",
            "AppBundle\\Service\\Interfaces\\PasswordGeneratorInterface",
            "AppBundle\\Service\\Interfaces\\MailerInterface"
        ],
        "parents": [
            "AppBundle\\Form\\Handler\\FormTypeHandler"
        ],
        "lcom": 2,
        "length": 35,
        "vocabulary": 11,
        "volume": 121.08,
        "difficulty": 3.11,
        "effort": 376.69,
        "level": 0.32,
        "bugs": 0.04,
        "time": 21,
        "intelligentContent": 38.92,
        "number_operators": 7,
        "number_operands": 28,
        "number_operators_unique": 2,
        "number_operands_unique": 9,
        "cloc": 24,
        "loc": 52,
        "lloc": 28,
        "mi": 97.14,
        "mIwoC": 53.71,
        "commentWeight": 43.43,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.33,
        "relativeSystemComplexity": 49.33,
        "totalStructuralComplexity": 147,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 148,
        "package": "AppBundle\\Form\\Handler\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 5,
        "instability": 0.83,
        "violations": {}
    },
    {
        "name": "AppBundle\\Form\\Handler\\UserUpdateTypeHandler",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "onSuccess",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getFormType",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "AppBundle\\Form\\Handler\\FormTypeHandler",
            "AppBundle\\Repository\\Interfaces\\UserRepositoryInterface",
            "AppBundle\\Service\\Interfaces\\MailerInterface"
        ],
        "parents": [
            "AppBundle\\Form\\Handler\\FormTypeHandler"
        ],
        "lcom": 2,
        "length": 16,
        "vocabulary": 8,
        "volume": 48,
        "difficulty": 2.17,
        "effort": 104,
        "level": 0.46,
        "bugs": 0.02,
        "time": 6,
        "intelligentContent": 22.15,
        "number_operators": 3,
        "number_operands": 13,
        "number_operators_unique": 2,
        "number_operands_unique": 6,
        "cloc": 18,
        "loc": 38,
        "lloc": 20,
        "mi": 103.48,
        "mIwoC": 59.71,
        "commentWeight": 43.77,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.67,
        "relativeSystemComplexity": 4.67,
        "totalStructuralComplexity": 12,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 14,
        "package": "AppBundle\\Form\\Handler\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "AppBundle\\Form\\ResetPasswordType",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "buildForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Component\\Form\\AbstractType",
            "Symfony\\Component\\Form\\FormBuilderInterface"
        ],
        "parents": [
            "Symfony\\Component\\Form\\AbstractType"
        ],
        "lcom": 1,
        "length": 16,
        "vocabulary": 13,
        "volume": 59.21,
        "difficulty": 0,
        "effort": 0,
        "level": 1.63,
        "bugs": 0.02,
        "time": 0,
        "intelligentContent": 96.21,
        "number_operators": 0,
        "number_operands": 16,
        "number_operators_unique": 0,
        "number_operands_unique": 13,
        "cloc": 7,
        "loc": 15,
        "lloc": 8,
        "mi": 111.33,
        "mIwoC": 67.76,
        "commentWeight": 43.58,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 2,
        "package": "AppBundle\\Form\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Form\\TaskAddType",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "buildForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Component\\Form\\AbstractType",
            "Symfony\\Component\\Form\\FormBuilderInterface"
        ],
        "parents": [
            "Symfony\\Component\\Form\\AbstractType"
        ],
        "lcom": 1,
        "length": 5,
        "vocabulary": 4,
        "volume": 10,
        "difficulty": 0,
        "effort": 0,
        "level": 1.6,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 16,
        "number_operators": 0,
        "number_operands": 5,
        "number_operators_unique": 0,
        "number_operands_unique": 4,
        "cloc": 7,
        "loc": 15,
        "lloc": 8,
        "mi": 116.74,
        "mIwoC": 73.16,
        "commentWeight": 43.58,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 2,
        "package": "AppBundle\\Form\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Form\\UserRegistrationType",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "buildForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Component\\Form\\AbstractType",
            "Symfony\\Component\\Form\\FormBuilderInterface"
        ],
        "parents": [
            "Symfony\\Component\\Form\\AbstractType"
        ],
        "lcom": 1,
        "length": 13,
        "vocabulary": 10,
        "volume": 43.19,
        "difficulty": 0,
        "effort": 0,
        "level": 1.54,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 66.44,
        "number_operators": 0,
        "number_operands": 13,
        "number_operators_unique": 0,
        "number_operands_unique": 10,
        "cloc": 7,
        "loc": 15,
        "lloc": 8,
        "mi": 112.29,
        "mIwoC": 68.71,
        "commentWeight": 43.58,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 2,
        "package": "AppBundle\\Form\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Listener\\ResponseListener",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "onKernelResponse",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Component\\HttpKernel\\Event\\FilterResponseEvent"
        ],
        "parents": [],
        "lcom": 1,
        "length": 7,
        "vocabulary": 3,
        "volume": 11.09,
        "difficulty": 1.5,
        "effort": 16.64,
        "level": 0.67,
        "bugs": 0,
        "time": 1,
        "intelligentContent": 7.4,
        "number_operators": 1,
        "number_operands": 6,
        "number_operators_unique": 1,
        "number_operands_unique": 2,
        "cloc": 6,
        "loc": 16,
        "lloc": 10,
        "mi": 111.37,
        "mIwoC": 70.73,
        "commentWeight": 40.63,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.25,
        "relativeSystemComplexity": 9.25,
        "totalStructuralComplexity": 9,
        "totalDataComplexity": 0.25,
        "totalSystemComplexity": 9.25,
        "package": "AppBundle\\Listener\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Repository\\TaskRepository",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isNewEntity",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "save",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "flush",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "delete",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "findAllTask",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepository",
            "AppBundle\\Repository\\Interfaces\\TaskRepositoryInterface",
            "Symfony\\Bridge\\Doctrine\\RegistryInterface",
            "parent",
            "AppBundle\\Entity\\Interfaces\\TaskInterface",
            "AppBundle\\Entity\\Interfaces\\TaskInterface",
            "this",
            "this",
            "AppBundle\\Entity\\Interfaces\\TaskInterface",
            "this"
        ],
        "parents": [
            "Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepository"
        ],
        "lcom": 3,
        "length": 34,
        "vocabulary": 14,
        "volume": 129.45,
        "difficulty": 7.78,
        "effort": 1006.83,
        "level": 0.13,
        "bugs": 0.04,
        "time": 56,
        "intelligentContent": 16.64,
        "number_operators": 6,
        "number_operands": 28,
        "number_operators_unique": 5,
        "number_operands_unique": 9,
        "cloc": 23,
        "loc": 57,
        "lloc": 34,
        "mi": 93.17,
        "mIwoC": 51.53,
        "commentWeight": 41.64,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 169,
        "relativeDataComplexity": 0.2,
        "relativeSystemComplexity": 169.2,
        "totalStructuralComplexity": 1014,
        "totalDataComplexity": 1.21,
        "totalSystemComplexity": 1015.21,
        "package": "AppBundle\\Repository\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Repository\\UserRepository",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "save",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUserByEmail",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUserByToken",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "listUsers",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepository",
            "AppBundle\\Repository\\Interfaces\\UserRepositoryInterface",
            "Symfony\\Bridge\\Doctrine\\RegistryInterface",
            "parent",
            "AppBundle\\Entity\\Interfaces\\UserInterface"
        ],
        "parents": [
            "Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepository"
        ],
        "lcom": 3,
        "length": 39,
        "vocabulary": 15,
        "volume": 152.37,
        "difficulty": 5.64,
        "effort": 858.81,
        "level": 0.18,
        "bugs": 0.05,
        "time": 48,
        "intelligentContent": 27.03,
        "number_operators": 8,
        "number_operands": 31,
        "number_operators_unique": 4,
        "number_operands_unique": 11,
        "cloc": 18,
        "loc": 49,
        "lloc": 31,
        "mi": 92.26,
        "mIwoC": 51.91,
        "commentWeight": 40.35,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 144,
        "relativeDataComplexity": 0.29,
        "relativeSystemComplexity": 144.29,
        "totalStructuralComplexity": 720,
        "totalDataComplexity": 1.46,
        "totalSystemComplexity": 721.46,
        "package": "AppBundle\\Repository\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Security\\TaskVoter",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "supports",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "voteOnAttribute",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "canDelete",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 3,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 10,
        "ccn": 8,
        "ccnMethodMax": 4,
        "externals": [
            "Symfony\\Component\\Security\\Core\\Authorization\\Voter\\Voter",
            "Symfony\\Component\\Security\\Core\\Authentication\\Token\\TokenInterface",
            "LogicException",
            "AppBundle\\Entity\\Interfaces\\TaskInterface",
            "AppBundle\\Entity\\Interfaces\\UserInterface"
        ],
        "parents": [
            "Symfony\\Component\\Security\\Core\\Authorization\\Voter\\Voter"
        ],
        "lcom": 2,
        "length": 42,
        "vocabulary": 16,
        "volume": 168,
        "difficulty": 9.72,
        "effort": 1633.33,
        "level": 0.1,
        "bugs": 0.06,
        "time": 91,
        "intelligentContent": 17.28,
        "number_operators": 17,
        "number_operands": 25,
        "number_operators_unique": 7,
        "number_operands_unique": 9,
        "cloc": 26,
        "loc": 61,
        "lloc": 35,
        "mi": 92.04,
        "mIwoC": 49.66,
        "commentWeight": 42.38,
        "kanDefect": 0.65,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 2.33,
        "relativeSystemComplexity": 11.33,
        "totalStructuralComplexity": 27,
        "totalDataComplexity": 7,
        "totalSystemComplexity": 34,
        "package": "AppBundle\\Security\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Service\\Mailer",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "sendMail",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getMailerFrom",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "AppBundle\\Service\\Interfaces\\MailerInterface",
            "Twig_Environment",
            "Swift_Mailer",
            "AppBundle\\Entity\\Interfaces\\UserInterface",
            "Swift_Message"
        ],
        "parents": [],
        "lcom": 1,
        "length": 33,
        "vocabulary": 14,
        "volume": 125.64,
        "difficulty": 3.55,
        "effort": 445.46,
        "level": 0.28,
        "bugs": 0.04,
        "time": 25,
        "intelligentContent": 35.44,
        "number_operators": 7,
        "number_operands": 26,
        "number_operators_unique": 3,
        "number_operands_unique": 11,
        "cloc": 21,
        "loc": 43,
        "lloc": 22,
        "mi": 100.04,
        "mIwoC": 55.88,
        "commentWeight": 44.16,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 81,
        "relativeDataComplexity": 0.3,
        "relativeSystemComplexity": 81.3,
        "totalStructuralComplexity": 243,
        "totalDataComplexity": 0.9,
        "totalSystemComplexity": 243.9,
        "package": "AppBundle\\Service\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Service\\PasswordGenerator",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "generate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "AppBundle\\Service\\Interfaces\\PasswordGeneratorInterface"
        ],
        "parents": [],
        "lcom": 1,
        "length": 8,
        "vocabulary": 7,
        "volume": 22.46,
        "difficulty": 1.2,
        "effort": 26.95,
        "level": 0.83,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 18.72,
        "number_operators": 2,
        "number_operands": 6,
        "number_operators_unique": 2,
        "number_operands_unique": 5,
        "cloc": 9,
        "loc": 19,
        "lloc": 10,
        "mi": 112.36,
        "mIwoC": 68.59,
        "commentWeight": 43.77,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "AppBundle\\Service\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Service\\TokenGenerator",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "generateToken",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "AppBundle\\Service\\Interfaces\\TokenGeneratorInterface",
            "AppBundle\\Entity\\Interfaces\\UserInterface"
        ],
        "parents": [],
        "lcom": 1,
        "length": 9,
        "vocabulary": 6,
        "volume": 23.26,
        "difficulty": 2.5,
        "effort": 58.16,
        "level": 0.4,
        "bugs": 0.01,
        "time": 3,
        "intelligentContent": 9.31,
        "number_operators": 4,
        "number_operands": 5,
        "number_operators_unique": 3,
        "number_operands_unique": 3,
        "cloc": 6,
        "loc": 15,
        "lloc": 9,
        "mi": 111,
        "mIwoC": 69.48,
        "commentWeight": 41.52,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 2,
        "package": "AppBundle\\Service\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    }
]